export const data = [
  {
    DataProvider: {
      WebsiteURL: 'http://openchargemap.org',
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: 'Manual Data Entry',
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License:
        'Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)',
      DateLastImported: null,
      ID: 1,
      Title: 'Open Charge Map Contributors',
    },
    OperatorInfo: {
      WebsiteURL: null,
      Comments: null,
      PhonePrimaryContact: null,
      PhoneSecondaryContact: null,
      IsPrivateIndividual: null,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: null,
      FaultReportEmail: null,
      IsRestrictedEdit: null,
      ID: 1,
      Title: '(Unknown Operator)',
    },
    UsageType: {
      IsPayAtLocation: null,
      IsMembershipRequired: null,
      IsAccessKeyRequired: null,
      ID: 1,
      Title: 'Public',
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: 'Operational',
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: 'Submission Published',
    },
    UserComments: [
      {
        ID: 28485,
        ChargePointID: 265072,
        CommentTypeID: 10,
        CommentType: {
          ID: 10,
          Title: 'General Comment',
        },
        UserName: 'ForumElettrico.it',
        Comment:
          'Il parcheggio è quello del centro commerciale Il Volo ove si trovano uffici e negozi, e proprio di fronte alla colonnina abbiamo un comodo bar. Leggi la recensione completa qui: https://www.forumelettrico.it/forum/colonnina-irengo-22-kw-il-volo-reggio-emilia-re-largo-giambellino-3-t31434.html',
        Rating: null,
        RelatedURL:
          'https://www.forumelettrico.it/forum/colonnina-irengo-22-kw-il-volo-reggio-emilia-re-largo-giambellino-3-t31434.html',
        DateCreated: '2023-05-04T13:48:56.473Z',
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        CheckinStatusTypeID: 10,
        CheckinStatusType: {
          IsPositive: true,
          IsAutomatedCheckin: false,
          ID: 10,
          Title: 'Charged Successfully',
        },
        IsActionedByEditor: false,
      },
    ],
    PercentageSimilarity: null,
    MediaItems: [
      {
        ID: 37657,
        ChargePointID: 265072,
        ItemURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.orig.2023050413493151.jpg',
        ItemThumbnailURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.thmb.2023050413493151.jpg',
        Comment: '',
        IsEnabled: true,
        IsVideo: false,
        IsFeaturedItem: false,
        IsExternalResource: false,
        MetadataValue: null,
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        DateCreated: '2023-05-04T13:50:00Z',
      },
      {
        ID: 37653,
        ChargePointID: 265072,
        ItemURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.orig.2023050413490543.jpg',
        ItemThumbnailURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.thmb.2023050413490543.jpg',
        Comment: '',
        IsEnabled: true,
        IsVideo: false,
        IsFeaturedItem: false,
        IsExternalResource: false,
        MetadataValue: null,
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        DateCreated: '2023-05-04T13:49:00Z',
      },
      {
        ID: 37654,
        ChargePointID: 265072,
        ItemURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.orig.2023050413491150.jpg',
        ItemThumbnailURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.thmb.2023050413491150.jpg',
        Comment: '',
        IsEnabled: true,
        IsVideo: false,
        IsFeaturedItem: false,
        IsExternalResource: false,
        MetadataValue: null,
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        DateCreated: '2023-05-04T13:49:00Z',
      },
      {
        ID: 37655,
        ChargePointID: 265072,
        ItemURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.orig.2023050413491862.jpg',
        ItemThumbnailURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.thmb.2023050413491862.jpg',
        Comment: '',
        IsEnabled: true,
        IsVideo: false,
        IsFeaturedItem: false,
        IsExternalResource: false,
        MetadataValue: null,
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        DateCreated: '2023-05-04T13:49:00Z',
      },
      {
        ID: 37656,
        ChargePointID: 265072,
        ItemURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.orig.2023050413492434.jpg',
        ItemThumbnailURL:
          'https://s3-ap-southeast-2.amazonaws.com/openchargemap/images/IT/OCM265072/OCM-265072.thmb.2023050413492434.jpg',
        Comment: '',
        IsEnabled: true,
        IsVideo: false,
        IsFeaturedItem: false,
        IsExternalResource: false,
        MetadataValue: null,
        User: {
          ID: 11749,
          IdentityProvider: null,
          Identifier: null,
          CurrentSessionToken: null,
          Username: 'ForumElettrico.it',
          Profile: null,
          Location: null,
          WebsiteURL: null,
          ReputationPoints: 16296,
          Permissions: null,
          PermissionsRequested: null,
          DateCreated: null,
          DateLastLogin: null,
          IsProfilePublic: null,
          IsEmergencyChargingProvider: null,
          IsPublicChargingProvider: null,
          Latitude: null,
          Longitude: null,
          EmailAddress: null,
          EmailHash: null,
          ProfileImageURL:
            'https://www.gravatar.com/avatar/8f482f7e667741b53f05b06210bca268?s=80&d=robohash',
          IsCurrentSessionTokenValid: null,
          APIKey: null,
          SyncedSettings: null,
        },
        DateCreated: '2023-05-04T13:49:00Z',
      },
    ],
    IsRecentlyVerified: true,
    DateLastVerified: '2023-05-04T13:50:00Z',
    ID: 265072,
    UUID: '44FCEAB0-FECD-4710-9440-67EBDD4F6971',
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 1,
    OperatorsReference: null,
    UsageTypeID: 1,
    UsageCost: null,
    AddressInfo: {
      ID: 265456,
      Title: 'IrenGo Il Volo Carrozzone',
      AddressLine1: 'Largo Giambellino 3',
      AddressLine2: null,
      Town: 'Reggio Emilia',
      StateOrProvince: 'RE',
      Postcode: null,
      CountryID: 112,
      Country: {
        ISOCode: 'IT',
        ContinentCode: 'EU',
        ID: 112,
        Title: 'Italy',
      },
      Latitude: 44.707948,
      Longitude: 10.605952,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL:
        'https://www.forumelettrico.it/forum/colonnina-irengo-22-kw-il-volo-reggio-emilia-re-largo-giambellino-3-t31434.html',
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 449315,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: 'IEC 62196-2 Type 2',
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: 'Type 2 (Socket Only)',
        },
        Reference: null,
        StatusTypeID: null,
        StatusType: null,
        LevelID: 2,
        Level: {
          Comments: 'Over 2 kW, usually non-domestic socket type',
          IsFastChargeCapable: false,
          ID: 2,
          Title: 'Level 2 : Medium (Over 2kW)',
        },
        Amps: null,
        Voltage: null,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: 'Alternating Current - Three Phase',
          ID: 20,
          Title: 'AC (Three-Phase)',
        },
        Quantity: 2,
        Comments: null,
      },
    ],
    NumberOfPoints: 1,
    GeneralComments: null,
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: '2023-05-04T13:50:00Z',
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: '2023-05-04T13:49:00Z',
    SubmissionStatusTypeID: 200,
  },
];
